name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer les dépendances et construire le projet
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      # Étape 3 : Vérifier que le dossier `dist/` existe
      - name: Check build output
        run: ls -la dist/

      # Étape 4 : Déploiement via FTP
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          local-dir: ${{ secrets.FTP_LOCAL_DIR }}
        env:
          FTP_VERBOSE: true
